### ISSUE TITLE
./configure not exists

### ISSUE THREAD

**Issue by leonylcatwork** [KelvinJin/libsox-iOS#1]
Hi there, try to build and got following error:
./build_ios: line 33: ./configure: No such file or directory

Maybe files has been changed in new commit of sox.

Cheers

**Comment by KelvinJin** [comment]
Hey, thanks for the feedback. There is an extra step you'll need to do beforehand.

You'll have to install `automake`, `autoconf` as well as `libtool`.
```
brew install automake
brew install autoconf
brew install libtool
```

and then, under the sox source folder, run `autoreconf -i` first to generate the `configure` bash script after which you can run `./build_ios`.

Let me know if this helps.

Thanks again for the valuable feedback, I've updated README to add the missing step.

**Comment by leonylcatwork** [comment]
Thanks mate for prompt reply.

That bit was cleared. Now I encounter the following (it repeats for every architecture):

checking build system type... x86_64-apple-darwin16.7.0
checking host system type... i686-apple-darwin
checking target system type... i686-apple-darwin
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for i686-apple-darwin-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for i686-apple-darwin-gcc... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... rm: conftest.dSYM: is a directory
yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether ln -s works... yes
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... no
checking for i686-apple-darwin-dumpbin... no
checking for i686-apple-darwin-link... no
checking for dumpbin... no
checking for link... link -dump
configure: WARNING: using cross tools not prefixed with host triplet
checking the name lister (nm) interface... rm: conftest.dSYM: is a directory
BSD nm
checking the maximum length of command line arguments... 196608
checking how to convert x86_64-apple-darwin16.7.0 file names to i686-apple-darwin format... func_convert_file_noop
checking how to convert x86_64-apple-darwin16.7.0 file names to toolchain format... func_convert_file_noop
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
checking for i686-apple-darwin-objdump... no
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for i686-apple-darwin-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for i686-apple-darwin-ar... no
checking for ar... ar
checking for archiver @FILE support... rm: conftest.dSYM: is a directory
no
checking for i686-apple-darwin-strip... strip
checking for i686-apple-darwin-ranlib... no
checking for ranlib... ranlib
checking command to parse nm output from gcc object... rm: conftest.dSYM: is a directory
failed
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for i686-apple-darwin-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking for i686-apple-darwin-dsymutil... no
checking for dsymutil... dsymutil
checking for i686-apple-darwin-nmedit... no
checking for nmedit... nmedit
checking for i686-apple-darwin-lipo... no
checking for lipo... lipo
checking for i686-apple-darwin-otool... no
checking for otool... otool
checking for i686-apple-darwin-otool64... no
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin dyld
checking how to hardcode library paths into programs... immediate
checking for dlopen in -ldl... yes
checking whether a program can dlopen itself... cross
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking whether to make a debug build... 
checking whether libssp exists... no
checking whether stack-smashing protection is available... yes
checking whether stack-smashing protection is buggy... yes
checking gcc version... 4.2.1
checking whether byte ordering is bigendian... no
checking for inline... inline
checking for ANSI C header files... (cached) yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for unistd.h... (cached) yes
checking byteswap.h usability... no
checking byteswap.h presence... no
checking for byteswap.h... no
checking for sys/stat.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking sys/timeb.h usability... yes
checking sys/timeb.h presence... yes
checking for sys/timeb.h... yes
checking for sys/types.h... (cached) yes
checking sys/utsname.h usability... yes
checking sys/utsname.h presence... yes
checking for sys/utsname.h... yes
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking glob.h usability... yes
checking glob.h presence... yes
checking for glob.h... yes
checking fenv.h usability... yes
checking fenv.h presence... yes
checking for fenv.h... yes
checking for strcasecmp... yes
checking for strdup... yes
checking for popen... yes
checking for vsnprintf... yes
checking for gettimeofday... yes
checking for mkstemp... yes
checking for fmemopen... yes
checking for library containing pow... none required
checking for library containing lrint... none required
checking for lrint... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for _LARGEFILE_SOURCE value needed for large files... no
checking whether libtool should be silenced... yes
checking for gcc option to support OpenMP... unsupported
checking magic.h usability... no
checking magic.h presence... no
checking for magic.h... no
checking png.h usability... no
checking png.h presence... no
checking for png.h... no
checking libpng/png.h usability... no
checking libpng/png.h presence... no
checking for libpng/png.h... no
checking mad.h usability... no
checking mad.h presence... no
checking for mad.h... no
checking whether to dlopen mad... no
checking for mad_stream_buffer in -lmad... no
checking id3tag.h usability... no
checking id3tag.h presence... no
checking for id3tag.h... no
checking whether to dlopen lame... no
checking lame/lame.h usability... no
checking lame/lame.h presence... no
checking for lame/lame.h... no
checking lame.h usability... no
checking lame.h presence... no
checking for lame.h... no
checking for lame_get_lametag_frame in -lmp3lame... no
checking for id3tag_set_fieldvalue in -lmp3lame... no
checking twolame.h usability... no
checking twolame.h presence... no
checking for twolame.h... no
checking whether to dlopen twolame... no
checking for twolame_init in -ltwolame... no
checking gsm/gsm.h usability... no
checking gsm/gsm.h presence... no
checking for gsm/gsm.h... no
checking gsm.h usability... no
checking gsm.h presence... no
checking for gsm.h... no
checking for gsm_create in -lgsm... no
checking lpc10.h usability... no
checking lpc10.h presence... no
checking for lpc10.h... no
checking for lpc10.h... (cached) no
checking for create_lpc10_encoder_state in -llpc10... no
checking vorbis/codec.h usability... no
checking vorbis/codec.h presence... no
checking for vorbis/codec.h... no
./configure: line 15073: syntax error near unexpected token `OPUS,'
./configure: line 15073: `    PKG_CHECK_MODULES(OPUS, opusfile, , using_opus=no)'
make: Nothing to be done for `install'.

**Comment by leonylcatwork** [comment]
Update: I have done everything from scratch again and the script works. Cheers

**Comment by KelvinJin** [comment]
Glad to know. Thanks!
